name: 09 - Using Functions

on:
  puul_request:
  workflow_request:

jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: Failing step
        run: exit 1

      - name: I will be skipped
        if: ${{ success() }}
        run: echo "I wiil print of previous steps succeed"
      
      - name: I will execute
        if: ${{ !success() }}
        run: echo "I will print if any previous step fails"

      - name: I will execute
      if: ${{! cancelled() }}
        run: echo "i will always print, except when the workflow is cancelled"

      - name: I will execute when cancelled
        if: ${{ cancelled() }}