name: 11 - Working with Inputs
on:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        default: false
        description: Skip deployment and only print build output
      
      target:
        type: environment
        required: true
        description: which environment the worflow will target

      tag:
        type: choice
        default: v3
        description: release from which to build and deploy
        options: [v1, v2, v3]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: BUILD
        run: echo "Building from tag ${{ inputs.tag }}"
  
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target }}
    needs:
      - build
    if: ${{ !inputs.dry-run }}

    steps:
      - name: Deploy
        run: echo "Deploying to ${{ inputs.target }}"
